baseurl = "http://petschau.github.io/WinFellow"
languageCode = "en-us"
title = "WinFellow - Amiga Emulator for Windows"
theme = "twentyfourteen-tags"

[taxonomies]
tag = "tags"

[[menu.main]]
name = "Downloads"
weight = 10
url = "https://github.com/petschau/WinFellow/releases"

[[menu.main]]
name = "GitHub"
weight = 30
identifier = "GitHub"
url = "http://github.com/petschau/WinFellow"

[[menu.main]]
name = "sf.net Archive"
weight = 35
url = "http://fellow.sf.net/new_version"